// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XFLRNxAtws4OGramYHYXKwMI2HFY404',
    appId: '1:200117941914:web:9c3379e14b161283bd5123',
    messagingSenderId: '200117941914',
    projectId: 'drivingschool-5f348',
    authDomain: 'drivingschool-5f348.firebaseapp.com',
    databaseURL: 'https://drivingschool-5f348-default-rtdb.firebaseio.com',
    storageBucket: 'drivingschool-5f348.firebasestorage.app',
    measurementId: 'G-ECVPP97CNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdG-JkloQUq1b_ctdP7sH1ODdDSV8FCg',
    appId: '1:200117941914:android:ba36b7ecd37a4c92bd5123',
    messagingSenderId: '200117941914',
    projectId: 'drivingschool-5f348',
    databaseURL: 'https://drivingschool-5f348-default-rtdb.firebaseio.com',
    storageBucket: 'drivingschool-5f348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UlIFSHbPvVL0GBWTKfzAuuvN5t6F4P4',
    appId: '1:200117941914:ios:9a038624fccb4497bd5123',
    messagingSenderId: '200117941914',
    projectId: 'drivingschool-5f348',
    databaseURL: 'https://drivingschool-5f348-default-rtdb.firebaseio.com',
    storageBucket: 'drivingschool-5f348.firebasestorage.app',
    androidClientId: '200117941914-70koojond9bd905kjafpbp3hh3hitoer.apps.googleusercontent.com',
    iosClientId: '200117941914-tdmpga28u01ql0gprink5cbi7bu0te9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivingschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UlIFSHbPvVL0GBWTKfzAuuvN5t6F4P4',
    appId: '1:200117941914:ios:9a038624fccb4497bd5123',
    messagingSenderId: '200117941914',
    projectId: 'drivingschool-5f348',
    databaseURL: 'https://drivingschool-5f348-default-rtdb.firebaseio.com',
    storageBucket: 'drivingschool-5f348.firebasestorage.app',
    androidClientId: '200117941914-70koojond9bd905kjafpbp3hh3hitoer.apps.googleusercontent.com',
    iosClientId: '200117941914-tdmpga28u01ql0gprink5cbi7bu0te9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivingschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2XFLRNxAtws4OGramYHYXKwMI2HFY404',
    appId: '1:200117941914:web:15521530b6a16a3bbd5123',
    messagingSenderId: '200117941914',
    projectId: 'drivingschool-5f348',
    authDomain: 'drivingschool-5f348.firebaseapp.com',
    databaseURL: 'https://drivingschool-5f348-default-rtdb.firebaseio.com',
    storageBucket: 'drivingschool-5f348.firebasestorage.app',
    measurementId: 'G-6P6B35YFWV',
  );

}